# .github/workflows/node.js.yml
name: Node.js CI

# یہ Workflow کب چلے گا
on:
  push:
    branches: [ "main", "develop" ] # جب 'main' یا 'develop' برانچ میں کوڈ پش ہو
  pull_request:
    branches: [ "main" ] # جب 'main' میں پل ریکویسٹ آئے

# Workflow کے jobs
jobs:
  build:

    runs-on: ubuntu-latest # یہ job ایک تازہ Ubuntu ماحول میں چلے گا

    strategy:
      # مختلف Node.js ورژنز پر ٹیسٹ کرنے کے لیے
      matrix:
        node-version: [18.x, 20.x] 
        # اگر آپ نے ٹیسٹ زیادہ ورژنز پر نہیں چلانا تو صرف [20.x] بھی رکھ سکتے ہیں

    steps:
    - uses: actions/checkout@v4 # 1. ریپوزیٹری کا کوڈ نکالنا
      with:
        # اگر آپ کے سب ماڈیولز ہوں تو ضروری ہے
        submodules: true

    - name: Use Node.js ${{ matrix.node-version }} # 2. Node.js ورژن سیٹ کرنا
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # npm پیکیجز کو کیش کرے گا تاکہ دوبارہ انسٹالیشن تیزی سے ہو

    - name: Install Dependencies # 3. تمام لائبریریاں انسٹال کرنا
      run: npm install

    # [اہم نوٹ] اگر آپ کا Backend DB سے جڑتا ہے، تو ٹیسٹ سے پہلے Mock DB سیٹ اپ کرنا پڑتا ہے۔ 
    # سادہ ٹیسٹنگ کے لیے یہ کافی ہے۔ 

    - name: Run Tests # 4. ٹیسٹ چلانا
      # اگر آپ نے 'package.json' میں "test" سکرپٹ سیٹ کیا ہے (جیسے 'jest' یا 'mocha')
      run: npm test
      # اگر آپ کے پاس فی الحال کوئی ٹیسٹ نہیں ہے، تو آپ اس step کو عارضی طور پر ہٹا سکتے ہیں، 
      # لیکن جلد ہی ٹیسٹ شامل کرنا ضروری ہے۔

    - name: Lint Code (Optional) # 5. کوڈ کی صفائی کی جانچ (اگر آپ ESLint استعمال کرتے ہیں)
      # اگر آپ نے Linting سیٹ اپ کیا ہے تو یہاں کمانڈ شامل کریں۔
      # run: npm run lint
      run: echo "Linting step skipped for now. Add 'npm run lint' later."
